# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bda7ed7a9d8db9d71273dcf782752187a2a83be1a04b3c79b124137f107c6a1a1176b0853b49b020baa27afc184d1c8d62644efe15e75e3b7289ea0ea68046a

test:
  secret_key_base: e716f61ea5587e1df278503b2cfdf440e1f62ebf0e69f8967fb85d36f418bc23aa1439886775c96a91e77db24fb4c910b973bc226b19de9f9b31d1843fc49e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
